---
title: "Paper on the carbonate chemistry at Ny-Ålesund" 
author: "Jean-Pierre Gattuso, Samir Alliouane and Philipp Fischer"
date: '`r format(Sys.Date(), "%d %B %Y")`'
output:
  rmarkdown::html_document:
    theme: paper
    number_sections: false
fig_width: 12 
fig_height: 8     
---

```{r set-up, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
Sys.setlocale("LC_ALL", "en_US.UTF-8")
Sys.setenv(TZ='UTC') # on utilise UTC
rm(list = ls())
library(tidyverse)
#library(robfilter)
library(seacarb)
library(gridExtra)
library(lubridate)
#library(lmtest)
#library(grid)
library(viridis)
#library(dygraphs)
require("knitr")
library("lmodel2")
#library(captioner)
#library(xts)
#library(seismicRoll)
library(scales)
library(plotly)
library(htmlwidgets)
library(tsibble)
if (!require("directlabels")) install.packages("directlabels")
library("directlabels")
if (!require("pangaear")) install.packages("pangaear")
library("pangaear")
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_knit$set(root.dir = normalizePath("/Users/gattuso/not_synced_git/AWIPEV-CO2-git")) 

#knitr::opts_chunk$set(fig.width=12, fig.height=8) 

#fig_nums <- captioner()
#table_nums <- captioner(prefix = "Table")

#define who is the user and define paths
if (Sys.getenv("LOGNAME") == "gattuso") path_data = "../../pCloud\ Sync/Documents/experiments/exp168_awipev-CO2/"
if (Sys.getenv("LOGNAME") == "gattuso") path_fig = "/Users/gattuso/pCloud\ Sync/Documents/publications/publications_inpreparation/gattuso_etal_awipev-CO2/figures/"
if (Sys.getenv("LOGNAME") == "samir") path_data = "../../pCloud\ Sync/exp168_awipev-CO2/"


######## function to make regression plot with model I equation in title
ggreg <- function (fit, point_size=2) {
  ggplot(fit$model, aes_string(x = names(fit$model)[2],
                               y = names(fit$model)[1])) +
    geom_point(size = point_size, col = "blue") +
    stat_smooth(method = "lm", col = "black") +
    labs(title = paste(title, "\nAdj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                       "; Intercept =",signif(fit$coef[[1]],5 ),
                       "; Slope =",signif(fit$coef[[2]], 5),
                       "; P =",signif(summary(fit)$coef[2,4], 5))) +
    theme(plot.title = element_text(size=7))
}

#################### which.closest function
which.closest <- function(x, table, ...) {
  round(approx(x=table, y=1:length(table), xout=x, ...)$y)
}

#################### Regression function
# function regression plot with model II equation (MA) in title
## Dans labs ajout de la variable TITRE pour mettre titre avant chaque graphe
ggreg2 <- function (fit, xdata, ydata) { # x and y are the names of the variables
  fit_data <- data.frame(fit$x, fit$y)
  colnames(fit_data) = c(xdata, ydata)
reg <- fit$regression.results[2,] #one selects MA only
intercept <- reg$Intercept
slope <- reg$Slope
  ggplot(data = fit_data, aes_string(x = xdata, y = ydata)) + 
  geom_point(size = 2, col = "blue") +
  geom_abline(aes(intercept = fit$regression.results[2,2], slope = fit$regression.results[2,3]),
              colour = "blue")  + 
  labs(title = paste(titre,"\n Adj R2 = ", signif(fit$rsquare, 3),
                     "; Intercept =", signif(intercept, 3),
                     "; Slope =", signif(slope, 3),
                     "; P =", signif(fit$P.param, 3)))
}

mytheme <- theme_bw() +
  theme(axis.text.x=element_text(size=16, color="black"),
        axis.title.x=element_text(face="bold", size=16),
        axis.text.y=element_text(size=16, color="black"),
        axis.title.y=element_text(face="bold", size=16),
        plot.title = element_text(face="bold", size=14)
)

#################### Mytheme
Mytheme <- function(size_labs = 7, face_font="plain") {
  theme_bw() +
  theme(axis.text.x = element_text(face=face_font, size=size_labs, color="black"),
        axis.title.x = element_text(face=face_font, size=size_labs),
        axis.text.y = element_text(face=face_font, color="black", size=size_labs),
        axis.title.y = element_text(face=face_font, size=size_labs),
        axis.ticks.x = element_line(size=0.1),
        axis.ticks.y = element_line(size=0.1),
        axis.ticks.length = unit(1.1, "mm"),
        panel.grid.major = element_line(size = 0.25, color="black", linetype="dashed"),
        #aspect.ratio = 1 / 3,
        plot.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm")
  )
}

ggplotRegression <- function(fit){
ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red", se= FALSE) +
  labs(title = paste("Adj R2 = ", signif(summary(fit)$adj.r.squared, 5),
                     "Intercept =", signif(fit$coef[[1]],5 ),
                     " Slope =", signif(fit$coef[[2]], 5),
                     " P =", signif(summary(fit)$coef[2,4], 5)))
}
```

```{r read and clean data, echo=FALSE, warning=FALSE, message=FALSE}
d_all <- as_tibble(readRDS(file = paste0(path_data, "fb_data/d_all_copy.rds"))) %>% 
  dplyr::filter(sal_fb > 28) %>% # remove salinity data lower than 28
  dplyr::mutate(year_month = format(datetime, '%Y-%m'))
```

## Whole time series
```{r whole time series, fig.width=10, fig.height=10, echo=FALSE, message= FALSE}
size_point <- 1 # size of data points

#SAL SBE45
ts_sal <- d_all %>%
  ggplot(aes(x = datetime, y = sal_fb), na.rm=TRUE) +
  scale_x_datetime(breaks = date_breaks("1 year"), labels = date_format("%Y")) +
  geom_point(colour="black", na.rm=TRUE, size=size_point) + 
  labs(title="Salinity FerryBox? SBE45",x="", y="Salinity") +
  #coord_fixed() +
  Mytheme(size_labs = 8)
ts_sal_py <- ggplotly(ts_sal,dynamicTicks = TRUE)
filename.html <- paste0(path_fig, "ts_sal_py.html")
saveWidget(ts_sal_py, filename.html, selfcontained = T, libdir = "lib")

# TEMP ferrybox
ts_temp <- d_all %>%
  ggplot(aes(x = datetime, y = temp_fb), na.rm=TRUE) +
  scale_x_datetime(breaks = date_breaks("1 year"), labels = date_format("%Y")) +
  geom_point(colour="black", na.rm=TRUE, size=size_point) + 
  labs(title="Temperature FerryBox",x="", y="In situ temperature (°C)") +
  #coord_fixed() +
  Mytheme(size_labs = 8)

# PCO2 
ts_pCO2 <- d_all %>%
  ggplot() +
  scale_x_datetime(breaks = date_breaks("1 year"), labels = date_format("%Y")) +
  geom_point(aes(x = datetime, y = pco2_contros), 
             colour="black", na.rm=TRUE, size=size_point) + 
  geom_point(aes(x = datetime, y = pco2calc), colour="blue", na.rm=TRUE, size=size_point) + 
  labs(title="CO2 partial pressure",x="", y="pCO2 (uatm)") +
  #coord_fixed() +
  Mytheme(size_labs = 8)

# SEAFET pH
ts_pH <- d_all %>%
  ggplot(aes(x = datetime, y = pHint_tot_sf), na.rm=TRUE) +
  scale_x_datetime(breaks = date_breaks("1 year"), labels = date_format("%Y")) +
  geom_point(colour="black", na.rm=TRUE, size=size_point) + 
  labs(title="In situ pH",x="", y="pCO2 (uatm)") +
  #coord_fixed() +
  Mytheme(size_labs = 8)

# TA
ts_at <- d_all %>%
  ggplot(aes(x = datetime, y = at_calc), na.rm=TRUE) +
  scale_x_datetime(breaks = date_breaks("1 year"), labels = date_format("%Y")) +
  geom_point(colour="black", na.rm=TRUE, size=size_point) + 
  labs(title="Total alkalinity calculated from salinity", x="", y="AT (umol/kg)") +
  #coord_fixed() +
  Mytheme(size_labs = 8)

g <- cowplot::plot_grid(ts_sal, ts_temp, ts_pCO2, ts_pH, ts_at, align='v', ncol=1)
print(g)
```

#Temperature vs salinity
We explore the use of a TS diagram to investigate changes in water sources. Monthly slopes of the T vs S plots are calculated. It seems that slopes are mostly not significant in winter and that they can be both positive and negative in summer.

```{r temperature vs salinity plots, fig.width=8, fig.height=8, echo=FALSE, message= FALSE}
# One tries to identify water masses coming from the Atlantic or freshwater
s <- c(seq(30.4, 35.3, length.out = 100)) # pCO2
t <- seq(-2, 8, length.out = 100) #temperature throughout the year
grid <- as_tibble(expand.grid(s=s, t=t))
grid$z <- rho(S = grid$s, T = grid$t, P = 1)

d <- d_all %>%
  dplyr::filter(year < 2020) %>%
  dplyr::mutate(month=month(datetime, label = TRUE, abbr = TRUE)) # abbreviated months rather than digital months
  #ggplot(aes(x = sal_fb, y = temp_insitu), na.rm=TRUE) +
temp_sal <-  ggplot() +
  geom_point(data = d, aes(x = sal_fb, y = temp_fb, fill=month), na.rm=TRUE,
             size=size_point, show.legend=FALSE) + 
  labs(title="Temperature vs salinity, both in FerryBox, blue lines show density", x="Salinity", y="Temp. (°C)") +
  facet_wrap(~ year, ncol = 3) +
  stat_smooth(data = d, aes(x = sal_fb, y = temp_fb, color=month),
              method=lm, na.rm=TRUE, se=FALSE) +
  scale_color_viridis(name="Month", discrete=TRUE, option="plasma") +
  geom_contour(data = grid, aes(x = s, y = t, z = z), 
               stat = "contour", binwidth=1, show.legend=FALSE, na.rm=TRUE) +
  scale_x_continuous(limits = c(30.4, 35.3), expand = c(0,0) ) +
  scale_y_continuous(limits = c(-2,8.5), expand = c(0,0) ) +
  coord_fixed() +
  annotate("text", label="Fresh and cold", x=31.5, y=-1.5) +
  annotate("text", label="Salty and warm", x=34.5, y=8.1) +
  Mytheme(size_labs = 10)
ggsave(temp_sal,filename = paste0(path_fig, "temp_sal.png"), width = 20, height = 20 ,units="cm")
temp_sal_py <- ggplotly(temp_sal,dynamicTicks = TRUE)
filename.html <- paste0(path_fig, "temp_sal_py.html")
saveWidget(temp_sal_py, filename.html, selfcontained = T, libdir = "lib")
```
print(temp_sal)

```{r temperature vs salinity regressions, fig.width=6, fig.height=6, echo=FALSE, message= FALSE}
# AT as a function of salinity for every year
j <- 0
reg <- data.frame()
for (i in 1:length(unique(d$year_month))) { #one loops through all years
  j <- j + 1
  ym <- unique(d$year_month)[i]
  d_reg <- filter(d, year_month==ym)
  if (length(!is.na(d_reg$temp_fb)) > 2) { #there is no temp_insitu in 2016-08, hence skip. Not needed if one uses temp_fb
  lms <- summary(lm(data=d_reg, sal_fb ~ temp_fb))
  # calculate probability of fstatistic because it cannot be extracted from lms above
  # see http://stats.stackexchange.com/questions/92824/extracting-the-model-p-value-for-a-multiple-regression-in-r
  # slope returned by lm is per second
  prob <- pf(lms$fstatistic[1],lms$fstatistic[2],lms$fstatistic[3],lower.tail=FALSE)
  reg <- rbind(reg, as.numeric(c(lms$coefficients[2,1], lms$coefficients[2,2], 
                                 lms$coefficients[2,4], lms$coefficients[1,1], lms$coefficients[1,2],
                                 lms$coefficients[1,4], lms$fstatistic[1], lms$fstatistic[3], lms$r.squared, prob)))
  }
}
names(reg) <- c("Slope", "SE_Slope", "P Slope","Intercept","SE int.","P int.", "F", "df",
                "R2","P_value")
row.names(reg) <- as.character(unique(d$year_month))
#transform in latex table and save
tab_reg_temp_sal <- reg
tmp_reg_temp_sal <- reg %>% # to enable plotting below
  dplyr::mutate(date = as.Date(paste0(row.names(reg), "-01")),
                month = month(date, label=TRUE, abbr = TRUE))
#plot
fig_reg_temp_sal <- tmp_reg_temp_sal %>%
  dplyr::filter(P_value < .05) %>% #eliminate when correlation not significant
  ggplot() +
  labs(title = "Slope ± 2 x SE", subtitle = "3 months with correlation coefficient not significant were eliminated") +
  geom_point(aes(x=date, y=Slope, color=month, size=P_value)) +
  scale_color_viridis(discrete = TRUE) +
  #scale_fill_continuous(name="P value slope") +
  geom_hline(yintercept = 0) + 
  scale_size_continuous(range = c(3,7)) +
  geom_errorbar(aes(x=date, ymin=Slope-2*SE_Slope, ymax=Slope+2*SE_Slope), width=.2) +
  Mytheme(size_labs = 14) +
  guides(colour = guide_legend("Month", override.aes = list(size=4)), size = guide_legend("P value slope"))
fig_reg_temp_sal
```
kable(tab_reg_temp_sal)
print(fig_reg_temp_sal)


```{r density, fig.width=10, fig.height=10, echo=FALSE, message= FALSE}
# d_all <- d_all %>%
#   dplyr::mutate(den = den)
# ts_den <- d_all %>%
#   ggplot(aes(x = datetime, y = den), na.rm=TRUE) +
#   scale_x_datetime(breaks = date_breaks("1 year"), labels = date_format("%Y")) +
#   geom_point(colour="black", na.rm=TRUE, size=size_point) + 
#   labs(title="Density",x="Time", y="Density") +
#   #coord_fixed() +
#   Mytheme(size_labs = 14)
# print(ts_den)
```

```{r pangaea data, fig.width=10, fig.height=10, echo=FALSE, message= FALSE}
data_2015 <- pg_data(doi="10.1594/PANGAEA.896771", overwrite = TRUE)
data_2016 <- pg_data(doi="10.1594/PANGAEA.896770", overwrite = TRUE)
data_2017 <- pg_data(doi="10.1594/PANGAEA.896170", overwrite = TRUE)
data_2018 <- pg_data(doi="10.1594/PANGAEA.897349", overwrite = TRUE)
tmp <- rbind(data_2015[[1]]$data, data_2016[[1]]$data, data_2017[[1]]$data, data_2018[[1]]$data)
tmp <- tmp[, c(1,8)] # select date time and salinity
tmp$`Date/Time` <- as.POSIXct(strptime(tmp$`Date/Time`, "%Y-%m-%dT%H:%M", tz = "UTC"))

all_data <- tmp %>%
  dplyr::filter(!are_duplicated(tmp)) %>%
  dplyr::rename(datetime = `Date/Time`,
                sal = `Sal ([PSU])`) %>%
  as_tsibble(key = NULL, index = datetime) %>%
  fill_gaps()

all_data %>%
  ggplot() +
  geom_point(aes(x=datetime, y=sal), na.rm = TRUE)
```


